language: python
python:
  - '3.6.9'

# safelist
branches:
  only:
    - staging


before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="oc13.settings.travis"

script:
  - cd oc13
  - ./manage.py test