# Generated by Django 3.0.2 on 2020-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='outlay',
            name='payment_method',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
