# Generated by Django 3.0.2 on 2020-01-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0003_auto_20200123_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlay',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='outlay',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='outlay',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='outlay',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='useroutlay',
            name='outlay',
        ),
        migrations.CreateModel(
            name='OutlayField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('outlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spent.Outlay')),
            ],
        ),
        migrations.AddField(
            model_name='useroutlay',
            name='outlay_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spent.OutlayField'),
        ),
    ]
