# Generated by Django 3.0.2 on 2020-01-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0005_auto_20200126_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutlay',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Virement', 'Virement'), ('Prélèvement', 'Prélèvement'), ('Chèque', 'Chèque')], max_length=15, null=True),
        ),
    ]
