# Generated by Django 3.0.2 on 2020-01-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0006_auto_20200130_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutlay',
            name='payment_method',
            field=models.CharField(choices=[('Virement', 'Virement'), ('Prélèvement', 'Prélèvement'), ('Chèque', 'Chèque')], max_length=15, null=True),
        ),
    ]
