# Generated by Django 3.0.2 on 2020-02-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0007_auto_20200131_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutlay',
            name='payment_method',
            field=models.CharField(choices=[('Carte bancaire', 'Carte bancaire'), ('Espèce', 'Espèce'), ('Virement', 'Virement'), ('Prélèvement', 'Prélèvement'), ('Chèque', 'Chèque')], max_length=15, null=True),
        ),
    ]
